"""added active flag

Revision ID: 02aabcd5f580
Revises: 997a8f92fdd5
Create Date: 2022-01-19 17:10:52.921969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02aabcd5f580'
down_revision = '997a8f92fdd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'is_active')
    # ### end Alembic commands ###
