"""based personalization

Revision ID: 087bd366316f
Revises: 5c569db10f8d
Create Date: 2022-04-22 12:49:23.352406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087bd366316f'
down_revision = '5c569db10f8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personalization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('based_personalization_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_based_personalization', 'personalization', ['based_personalization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personalization', schema=None) as batch_op:
        batch_op.drop_constraint('fk_based_personalization', type_='foreignkey')
        batch_op.drop_column('based_personalization_id')

    # ### end Alembic commands ###
