"""added day count

Revision ID: 0c8407e4fb49
Revises: 9c33f83c00c3
Create Date: 2022-01-28 13:37:29.176556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8407e4fb49'
down_revision = '9c33f83c00c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_covered_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant_stats', schema=None) as batch_op:
        batch_op.drop_column('amount_covered_days')

    # ### end Alembic commands ###
