"""added tags

Revision ID: 120fa9a324bb
Revises: 997a8f92fdd5
Create Date: 2022-01-22 11:16:19.879378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120fa9a324bb'
down_revision = '997a8f92fdd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recording_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('icon_name', sa.String(length=128), nullable=True),
    sa.Column('icon_color', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('default_include_for_statistics', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants_tag_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('recording_tag_id', sa.Integer(), nullable=True),
    sa.Column('include_for_statistics', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.ForeignKeyConstraint(['recording_tag_id'], ['recording_tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recording_to_tag',
    sa.Column('recording_tag_id', sa.Integer(), nullable=True),
    sa.Column('recording_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recording_id'], ['recording.id'], ),
    sa.ForeignKeyConstraint(['recording_tag_id'], ['recording_tag.id'], )
    )
    op.add_column('participant', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('participant_stats', sa.Column('daily_duration', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('daily_count_hand_washes_total', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('daily_count_hand_washes_manual', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('daily_count_hand_washes_detected_total', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('daily_count_evaluation_yes', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('daily_count_evaluation_no', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant_stats', 'daily_count_evaluation_no')
    op.drop_column('participant_stats', 'daily_count_evaluation_yes')
    op.drop_column('participant_stats', 'daily_count_hand_washes_detected_total')
    op.drop_column('participant_stats', 'daily_count_hand_washes_manual')
    op.drop_column('participant_stats', 'daily_count_hand_washes_total')
    op.drop_column('participant_stats', 'daily_duration')
    op.drop_column('participant', 'is_active')
    op.drop_table('recording_to_tag')
    op.drop_table('participants_tag_setting')
    op.drop_table('recording_tag')
    # ### end Alembic commands ###
