"""Added participant stats

Revision ID: 14bdc8583245
Revises: d3b612dc4bb4
Create Date: 2022-01-13 16:38:26.536497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14bdc8583245'
down_revision = 'd3b612dc4bb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('count_hand_washes_total', sa.Integer(), nullable=True),
    sa.Column('count_hand_washes_manual', sa.Integer(), nullable=True),
    sa.Column('count_hand_washes_detected_total', sa.Integer(), nullable=True),
    sa.Column('count_evaluation_yes', sa.Integer(), nullable=True),
    sa.Column('count_evaluation_no', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant_stats')
    # ### end Alembic commands ###
