"""Added session size

Revision ID: 17459586148f
Revises: 52b5fcd8c768
Create Date: 2022-01-12 13:45:57.000560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17459586148f'
down_revision = '52b5fcd8c768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recording', sa.Column('session_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recording', 'session_size')
    # ### end Alembic commands ###
