"""added daily average

Revision ID: 1ba7b9cc6dcb
Revises: 02aabcd5f580
Create Date: 2022-01-19 17:53:33.014251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ba7b9cc6dcb'
down_revision = '02aabcd5f580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant_stats', sa.Column('daily_duration', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('daily_count_hand_washes_total', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('daily_count_hand_washes_manual', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('daily_count_hand_washes_detected_total', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('daily_count_evaluation_yes', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('daily_count_evaluation_no', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant_stats', 'daily_count_evaluation_no')
    op.drop_column('participant_stats', 'daily_count_evaluation_yes')
    op.drop_column('participant_stats', 'daily_count_hand_washes_detected_total')
    op.drop_column('participant_stats', 'daily_count_hand_washes_manual')
    op.drop_column('participant_stats', 'daily_count_hand_washes_total')
    op.drop_column('participant_stats', 'daily_duration')
    # ### end Alembic commands ###
