"""required personalization time

Revision ID: 2302f55de0c2
Revises: f9c2bf028d1c
Create Date: 2022-04-21 09:21:29.490858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2302f55de0c2'
down_revision = 'f9c2bf028d1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personalization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_time', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personalization', schema=None) as batch_op:
        batch_op.drop_column('required_time')

    # ### end Alembic commands ###
