"""Added recordings to database

Revision ID: 52b5fcd8c768
Revises: 69b60a3e2d6a
Create Date: 2022-01-12 12:26:28.094346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b5fcd8c768'
down_revision = '69b60a3e2d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('android_id', sa.String(length=256), nullable=True),
    sa.Column('alias', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recording',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('alias', sa.String(length=256), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('last_changed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ml_model', sa.String(length=256), nullable=True),
    sa.Column('ml_settings', sa.String(length=512), nullable=True),
    sa.Column('app_version', sa.String(length=64), nullable=True),
    sa.Column('version_code', sa.String(length=64), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('start_time_stamp', sa.Integer(), nullable=True),
    sa.Column('run_number', sa.Integer(), nullable=True),
    sa.Column('recording_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recording.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant_to_recording',
    sa.Column('recording_id', sa.Integer(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.ForeignKeyConstraint(['recording_id'], ['recording.id'], )
    )
    op.create_table('recording_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('count_hand_washes_total', sa.Integer(), nullable=True),
    sa.Column('count_hand_washes_manual', sa.Integer(), nullable=True),
    sa.Column('count_hand_washes_detected_total', sa.Integer(), nullable=True),
    sa.Column('count_evaluation_yes', sa.Integer(), nullable=True),
    sa.Column('count_evaluation_no', sa.Integer(), nullable=True),
    sa.Column('recording_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recording.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recording_stats')
    op.drop_table('participant_to_recording')
    op.drop_table('meta_info')
    op.drop_table('recording')
    op.drop_table('participant')
    # ### end Alembic commands ###
