"""added recording tags

Revision ID: 52f88cc883dc
Revises: 1ba7b9cc6dcb
Create Date: 2022-01-19 18:22:17.089519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f88cc883dc'
down_revision = '1ba7b9cc6dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recording_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('icon_name', sa.String(length=128), nullable=True),
    sa.Column('icon_color', sa.String(length=256), nullable=True),
    sa.Column('consider_for_stats', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recording_tag')
    # ### end Alembic commands ###
