"""personalization metrics

Revision ID: 5c569db10f8d
Revises: 2302f55de0c2
Create Date: 2022-04-22 10:54:52.327003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c569db10f8d'
down_revision = '2302f55de0c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personalization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sensitivity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('precision', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('f1', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personalization', schema=None) as batch_op:
        batch_op.drop_column('f1')
        batch_op.drop_column('precision')
        batch_op.drop_column('sensitivity')

    # ### end Alembic commands ###
