"""added personalization flag

Revision ID: 68bf0a071433
Revises: c44ad95d2d4c
Create Date: 2022-03-30 09:32:16.123803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68bf0a071433'
down_revision = 'c44ad95d2d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_personalization', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_column('enable_personalization')

    # ### end Alembic commands ###
