"""initial migration

Revision ID: 997a8f92fdd5
Revises: 
Create Date: 2022-01-14 10:04:48.876614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997a8f92fdd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authentication_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=256), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('meta_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ml_model', sa.String(length=256), nullable=True),
    sa.Column('ml_settings', sa.String(length=512), nullable=True),
    sa.Column('app_version', sa.String(length=64), nullable=True),
    sa.Column('version_code', sa.String(length=64), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('start_time_stamp', sa.Integer(), nullable=True),
    sa.Column('run_number', sa.Integer(), nullable=True),
    sa.Column('android_id', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('count_hand_washes_total', sa.Integer(), nullable=True),
    sa.Column('count_hand_washes_manual', sa.Integer(), nullable=True),
    sa.Column('count_hand_washes_detected_total', sa.Integer(), nullable=True),
    sa.Column('count_evaluation_yes', sa.Integer(), nullable=True),
    sa.Column('count_evaluation_no', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recording_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('count_hand_washes_total', sa.Integer(), nullable=True),
    sa.Column('count_hand_washes_manual', sa.Integer(), nullable=True),
    sa.Column('count_hand_washes_detected_total', sa.Integer(), nullable=True),
    sa.Column('count_evaluation_yes', sa.Integer(), nullable=True),
    sa.Column('count_evaluation_no', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('android_id', sa.String(length=256), nullable=True),
    sa.Column('alias', sa.String(length=256), nullable=True),
    sa.Column('stats_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stats_id'], ['participant_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recording',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('alias', sa.String(length=256), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('last_changed', sa.DateTime(), nullable=True),
    sa.Column('session_size', sa.Integer(), nullable=True),
    sa.Column('stats_id', sa.Integer(), nullable=True),
    sa.Column('meta_info_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meta_info_id'], ['meta_info.id'], ),
    sa.ForeignKeyConstraint(['stats_id'], ['recording_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant_to_recording',
    sa.Column('recording_id', sa.Integer(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.ForeignKeyConstraint(['recording_id'], ['recording.id'], )
    )
    op.create_table('recording_evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compulsive', sa.Boolean(), nullable=True),
    sa.Column('tense', sa.Integer(), nullable=True),
    sa.Column('urge', sa.Integer(), nullable=True),
    sa.Column('recording_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recording.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recording_evaluation')
    op.drop_table('participant_to_recording')
    op.drop_table('recording')
    op.drop_table('participant')
    op.drop_table('recording_stats')
    op.drop_table('participant_stats')
    op.drop_table('meta_info')
    op.drop_table('authentication_request')
    # ### end Alembic commands ###
