"""save pseudo labelfilter

Revision ID: a36bfd52ba6f
Revises: 11b6eb911454
Create Date: 2022-04-01 09:08:53.501411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a36bfd52ba6f'
down_revision = '11b6eb911454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personalization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_filter', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personalization', schema=None) as batch_op:
        batch_op.drop_column('used_filter')

    # ### end Alembic commands ###
