"""regularization flag

Revision ID: b5f8eb3276fa
Revises: 087bd366316f
Create Date: 2022-05-03 15:35:46.832011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f8eb3276fa'
down_revision = '087bd366316f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personalization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_regularization', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personalization', schema=None) as batch_op:
        batch_op.drop_column('used_regularization')

    # ### end Alembic commands ###
