"""added personalization

Revision ID: c44ad95d2d4c
Revises: 3b724196e33c
Create Date: 2022-03-29 13:13:37.286726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c44ad95d2d4c'
down_revision = '3b724196e33c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personalization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('iteration', sa.Integer(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('mean_threshold', sa.Float(), nullable=True),
    sa.Column('mean_kernel_width', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recording_for_personalization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personalization_id', sa.Integer(), nullable=False),
    sa.Column('recording_id', sa.Integer(), nullable=True),
    sa.Column('used_for_training', sa.Boolean(), nullable=True),
    sa.Column('used_for_testing', sa.Boolean(), nullable=True),
    sa.Column('unusable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['personalization_id'], ['personalization.id'], ),
    sa.ForeignKeyConstraint(['recording_id'], ['recording.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recording_for_personalization')
    op.drop_table('personalization')
    # ### end Alembic commands ###
