"""Added android id to metainfo

Revision ID: d3b612dc4bb4
Revises: 17459586148f
Create Date: 2022-01-12 14:12:50.774604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3b612dc4bb4'
down_revision = '17459586148f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meta_info', sa.Column('android_id', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meta_info', 'android_id')
    # ### end Alembic commands ###
