"""missed foreignkey

Revision ID: da74c5cc9430
Revises: 14bdc8583245
Create Date: 2022-01-13 16:44:56.380041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da74c5cc9430'
down_revision = '14bdc8583245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('stats_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'participant', 'participant_stats', ['stats_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participant', type_='foreignkey')
    op.drop_column('participant', 'stats_id')
    # ### end Alembic commands ###
