"""more tag setting states

Revision ID: f2525e71bdbb
Revises: 120fa9a324bb
Create Date: 2022-01-22 16:19:29.481074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2525e71bdbb'
down_revision = '120fa9a324bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants_tag_setting', sa.Column('not_include_for_statistics', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants_tag_setting', 'not_include_for_statistics')
    # ### end Alembic commands ###
